### ISSUE TITLE
FFI bindings for maliput::api::rules::BulbGroup

### ISSUE THREAD

**Issue by francocipollone** [maliput/maliput-rs#102]
- [x] const Id& id() #104 
 - [x] UniqueBulbGroupId unique_id() #106 
 - [x] const InertialPosition& position_traffic_light() #104 
 - [x] const Rotation& orientation_traffic_light() #104 
 - [x] std::vector<const Bulb*> bulbs() #104 
 - [x] const Bulb* GetBulb(const Bulb::Id& id) #104  
 - [x] const TrafficLight* traffic_light() #104
