### ISSUE TITLE
Rust API for maliput::api::rules::BulbGroup

### ISSUE THREAD

**Issue by francocipollone** [maliput/maliput-rs#103]
- [x] id #104 
 - [x] unique_id #106 
 - [x] position_traffic_light #104 
 - [x] orientation_traffic_light #104 
 - [x] bulbs #104 
 - [x] get_bulb(id)  #104 
 - [x] traffic_light #104
