### ISSUE TITLE
FFI Bindings for maliput::api::rules::DiscreteValueRule

### ISSUE THREAD

**Issue by francocipollone** [maliput/maliput-rs#109]
- [x] const Id& id() const   ----- From Rule #107 
  - [x] const TypeId& type_id() const  ----- From Rule #107 
  - [x] const LaneSRoute& zone() const ----- From Rule https://github.com/maliput/maliput-rs/pull/122
  - [x] const std::vector<DiscreteValue>& states() const #107

**Comment by francocipollone** [comment]
Closed as completed
