### ISSUE TITLE
FFI bindings for maliput::api::rules::RoadRulebook

### ISSUE THREAD

**Issue by francocipollone** [maliput/maliput-rs#110]
Only binding new rule API:
- [x] QueryResults https://github.com/maliput/maliput-rs/issues/123
- [x] QueryResults FindRules(const std::vector<LaneSRange>& ranges, double tolerance) const #123 
- [x] QueryResults Rules() const https://github.com/maliput/maliput-rs/issues/123
- [x] DiscreteValueRule GetDiscreteValueRule(const Rule::Id& id) const #108 
- [x] RangeValueRule GetRangeValueRule(const Rule::Id& id) const  #113
