### ISSUE TITLE
Rust API for RoadRulebook

### ISSUE THREAD

**Issue by francocipollone** [maliput/maliput-rs#112]
- [x] QueryResults https://github.com/maliput/maliput-rs/issues/123
- [x] find_rules(ranges, tolerance) #123 
- [x] rules() https://github.com/maliput/maliput-rs/issues/123
- [x] get_discrete_value_rule(id) #108  
- [x] get_range_value_rule(id) #113
