### ISSUE TITLE
FFI Bindings for maliput::api::rules::RangeValueRule

### ISSUE THREAD

**Issue by francocipollone** [maliput/maliput-rs#115]
- [x] const Id& id() const   ----- From Rule #113  
  - [x] const TypeId& type_id() const  ----- From Rule #113  
  - [x] const LaneSRoute& zone() const ----- From Rule https://github.com/maliput/maliput-rs/pull/122
  - [x] const std::vector<Range>& states() const #113

**Comment by francocipollone** [comment]
closed as completed
