### ISSUE TITLE
FFI Bindings for maliput::api::rules::DiscreteValueRule::DiscreteValue

### ISSUE THREAD

**Issue by francocipollone** [maliput/maliput-rs#118]
- [x] severity --- from rule::state #108 
- [x] related_rules --- from rule::state #108  
- [x] related_unique_ids --- from rule::state #108  
- [x] states #108
