### ISSUE TITLE
FFI Bindings for maliput::api::rules::RangeValueRule::Range

### ISSUE THREAD

**Issue by francocipollone** [maliput/maliput-rs#119]
- [x] severity --- from rule::state #113 
- [x] related_rules --- from rule::state #113 
- [x] related_unique_ids --- from rule::state #113 
- [x] states #113
