### ISSUE TITLE
[META] Create Rust API for maliput

### ISSUE THREAD

**Issue by francocipollone** [maliput/maliput-rs#13]
### Summary

`maliput-sys` is providing low level bindings
We should create a high level package for creating a decent rustacean API for maliput that consumes the low level bindings.

### ToDo

- [ ] Create Rust API for maliput math classes.
- [ ] Create Rust API for maliput api classes.
- [ ] Create Rust API for maliput api rules classes.
