### ISSUE TITLE
Rust API for maliput::api::Lane class

### ISSUE THREAD

**Issue by francocipollone** [maliput/maliput-rs#38]
### Methods

- [x] id https://github.com/maliput/maliput-rs/pull/39
- [x] segment https://github.com/maliput/maliput-rs/pull/59
- [x] index https://github.com/maliput/maliput-rs/pull/47
- [x] to_left https://github.com/maliput/maliput-rs/pull/39
- [x] to_right https://github.com/maliput/maliput-rs/pull/39
- [x] length https://github.com/maliput/maliput-rs/pull/39
- [x] lane_bounds https://github.com/maliput/maliput-rs/pull/47
- [x] segment_bounds https://github.com/maliput/maliput-rs/pull/47
- [x] elevation_bounds  https://github.com/maliput/maliput-rs/pull/47
- [x] to_inertial_position #45 
- [x] to_lane_position https://github.com/maliput/maliput-rs/pull/47
- [x] to_segment_position https://github.com/maliput/maliput-rs/pull/47
- [x] get_orientation #45 
- [x] eval_motion_derivatives
- [x] get_branch_point #64 
- [x] get_confluent_branches #64
- [x] get_ongoing_branches #64
- [x] get_default_branch #64
- [x] contains https://github.com/maliput/maliput-rs/pull/47
