### ISSUE TITLE
[maliput-sys] [META]  Bindings on maliput api

### ISSUE THREAD

**Issue by francocipollone** [maliput/maliput-rs#4]
### Summary
Goes on top of #3 

Create bindings for maliput api

### To Do
 - [ ] Create bindings for maliput::math
 - [ ] Create bindings for maliput::api
 - [ ] Create bindings for maliput::api::rules
 - [ ] Create bindings for maliput::plugin
 - [ ] Create bindings for maliput::utility

### Guidelines
- Maliput API cpp uses extensively std::map and std::optional. For first iteration focus on creating the most trivial bindings. We will tackle those particular cases later on. Reference: https://cxx.rs/bindings.html
- Namespace
   - The bindings should be located under `maliput_sys::<namespace>::ffi`:
      - For example: `maliput_sys::api::ffi::RoadNetwork` or `maliput_sys::math::ffi::Vector3`
