### ISSUE TITLE
Rely on BCR for bringing maliput_malidrive

### ISSUE THREAD

**Issue by francocipollone** [maliput/maliput-rs#8]
### Summary

At the moment that #7 was created maliput_malidrive hadn't been part of the BCR so we had to use submodules
https://github.com/maliput/maliput-rs/blob/896f157298d5fab8130f95d3c4bf456f942bbfc9/maliput-sdk/build.rs#L58-L68

### Requisites:
 - https://github.com/maliput/maliput_malidrive/pull/269
 - New patch release of maliput_malidrive (0.2.1)
 - Update BCR with latest release (0.2.1)

### Tasks:
 - [ ] Add maliput_malidrive to MODULE.bazel file
 - [ ] Remove maliput_malidrive submodule
 - [ ] Remove custom build of maliput_malidrive in build.rs
