### ISSUE TITLE
Rust API for maliput::api::rules::TrafficLight

### ISSUE THREAD

**Issue by francocipollone** [maliput/maliput-rs#95]
- [x] id() #91 
- [x] position_road_network() #98 
- [x] orientation_road_network #98 
- [x] bulb_groups #104 
- [x] get_bulb_group #104

**Comment by francocipollone** [comment]
Closed as completed
